### ISSUE TITLE
Add cpanato as GitHub Admin for Sigstore GitHub Org

### ISSUE THREAD

**Issue by cpanato** [sigstore/TSC#12]
I've been working on Sigstore projects for some time and there are some tasks that I need to perform to set up the repositories properly that need admin access in order to fix/add/correct settings

Also, I'm working on some GitHub automation that will require admin permissions to import existing data.

And, also, to offload the founders of the Org, there are lots of requests that I ask them to perform, and that slows down a bit.

So, I'm proposing to add @cpanato as Github Admin for the whole Sigstore org

**Comment by dlorenc** [comment]
+1 for automating all the team management, the current system is opaque, error prone, and time consuming. I'm in favor of getting that moved to checked in configuration and automation. 

If we need to grant temporary admin permissions to set that up, I think it's a net win in the long run because it will allow us to reduce the number of people with those privileges over time.

**Comment by lukehinds** [comment]
Could this be done for a determined amount of time until work is complete?

**Comment by lukehinds** [comment]
p.s. we need to move from teams if we can kill teams, we are out of seats now.

**Comment by cpanato** [comment]
> Could this be done for a determined amount of time until work is complete?

yes sure, but I was thinking for more long term as well, but up to discussion

**Comment by lukehinds** [comment]
This is being handled by the new infra WG, so will close for now.
